// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

var Columns = struct {
	Ludoman struct {
		ID, LudomanNickname, TgID, Balance, Losses, TotalLost, TotalWon string
	}
}{
	Ludoman: struct {
		ID, LudomanNickname, TgID, Balance, Losses, TotalLost, TotalWon string
	}{
		ID:              "ludomanId",
		LudomanNickname: "ludomanNickname",
		TgID:            "tgId",
		Balance:         "balance",
		Losses:          "losses",
		TotalLost:       "totalLost",
		TotalWon:        "totalWon",
	},
}

var Tables = struct {
	Ludoman struct {
		Name, Alias string
	}
}{
	Ludoman: struct {
		Name, Alias string
	}{
		Name:  "ludomans",
		Alias: "t",
	},
}

type Ludoman struct {
	tableName struct{} `pg:"ludomans,alias:t,discard_unknown_columns"`

	ID              int    `pg:"ludomanId,pk"`
	LudomanNickname string `pg:"ludomanNickname,use_zero"`
	TgID            int64  `pg:"tgId,use_zero"`
	Balance         int64  `pg:"balance,use_zero"`
	Losses          int64  `pg:"losses,use_zero"`
	TotalLost       *int64 `pg:"totalLost"`
	TotalWon        *int64 `pg:"totalWon"`
}
