// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

var Columns = struct {
	Ludoman struct {
		ID, Balance string
	}
}{
	Ludoman: struct {
		ID, Balance string
	}{
		ID:      "ludomanNickname",
		Balance: "balance",
	},
}

var Tables = struct {
	Ludoman struct {
		Name, Alias string
	}
}{
	Ludoman: struct {
		Name, Alias string
	}{
		Name:  "ludomans",
		Alias: "t",
	},
}

type Ludoman struct {
	tableName struct{} `pg:"ludomans,alias:t,discard_unknown_columns"`

	ID      string `pg:"ludomanNickname,pk"`
	Balance *int   `pg:"balance"`
}
