BEGIN;
CREATE TABLE IF NOT EXISTS "transactions" (
                                              "transactionId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "fromLudomanId" int4 NOT NULL,
                                              "toLudomanId" int4 NOT NULL,
                                              "amount" int8 NOT NULL,
                                              "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "fk_fromLudomanId" FOREIGN KEY ("fromLudomanId")
    REFERENCES "ludomans" ("ludomanId"),
    CONSTRAINT "fk_toLudomanId" FOREIGN KEY ("toLudomanId")
    REFERENCES "ludomans" ("ludomanId")
    );
COMMIT;