-- =============================================================================
-- Diagram Name: apisrv
-- Created on: 30.03.2025 18:55:41
-- Diagram Version: 
-- =============================================================================

CREATE TABLE "ludomans" (
	"ludomanId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"ludomanNickname" varchar(255) NOT NULL,
	"balance" int8 NOT NULL DEFAULT 0,
	"losses" int8 NOT NULL DEFAULT 0,
	"totalLost" int8,
	"totalWon" int8,
	"tgId" int8,
	CONSTRAINT "Constraint0" UNIQUE("ludomanNickname"),
	CONSTRAINT "Constraint1" UNIQUE("tgId")
);

CREATE INDEX "IX_ludomans_ludomanNickName" ON "ludomans" USING HASH (
	"ludomanNickname"
);


CREATE INDEX "IX_ludomand_tgID" ON "ludomans" USING BTREE (
	"tgId"
);




