-- =============================================================================
-- Diagram Name: apisrv
-- Created on: 3/30/2025 7:03:50 PM
-- Diagram Version: 
-- =============================================================================

CREATE TABLE "ludomans" (
	"ludomanId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"ludomanNickname" varchar(255) NOT NULL,
	"tgId" int8 NOT NULL DEFAULT 0,
	"balance" int8 NOT NULL DEFAULT 0,
	"losses" int8 NOT NULL DEFAULT 0,
	"totalLost" int8,
	"totalWon" int8,
	CONSTRAINT "Constraint0" UNIQUE("ludomanNickname"),
	CONSTRAINT "Constraint1" UNIQUE("tgId")
);

CREATE INDEX "IX_ludomans_ludomanNickName" ON "ludomans" USING HASH (
	"ludomanNickname"
);


CREATE INDEX "IX_ludomans_tgID" ON "ludomans" USING BTREE (
	"tgId"
);

SELECT column_name
FROM information_schema.key_column_usage
WHERE table_name = 'ludomans' AND constraint_name = 'PRIMARY';
ALTER TABLE "ludomans" ADD PRIMARY KEY ("ludomanId");

CREATE TABLE IF NOT EXISTS "transactions" (
                                              "transactionId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "fromLudomanId" int4 NOT NULL,
                                              "toLudomanId" int4 NOT NULL,
                                              "amount" int8 NOT NULL,
                                              "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "fk_fromLudomanId" FOREIGN KEY ("fromLudomanId")
    REFERENCES "ludomans" ("ludomanId"),
    CONSTRAINT "fk_toLudomanId" FOREIGN KEY ("toLudomanId")
    REFERENCES "ludomans" ("ludomanId")
    );
