-- =============================================================================
-- Diagram Name: ludoman2
-- Created on: 4/28/2025 5:30:06 PM
-- Diagram Version: 
-- =============================================================================


CREATE TABLE "ludomans" (
	"ludomanId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"ludomanNickname" varchar(255) NOT NULL,
	"tgId" int8 NOT NULL DEFAULT 0,
	"balance" int8 NOT NULL DEFAULT 0,
	"losses" int8 NOT NULL DEFAULT 0,
	"totalLost" int8,
	"totalWon" int8,
	"adsWatched" int4 NOT NULL DEFAULT 0,
	CONSTRAINT "Constraint0" UNIQUE("ludomanNickname"),
	CONSTRAINT "Constraint1" UNIQUE("tgId"),
	PRIMARY KEY("ludomanId")
);

CREATE INDEX "IX_ludomans_ludomanNickName" ON "ludomans" USING HASH (
	"ludomanNickname"
);


CREATE INDEX "IX_ludomans_tgID" ON "ludomans" USING BTREE (
	"tgId"
);


CREATE TABLE "transactions" (
	"transactionId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"fromLudomanId" int4 NOT NULL,
	"toLudomanId" int4 NOT NULL,
	"amount" int8 NOT NULL,
	"createdAt" timestamp NOT NULL DEFAULT now(),
	PRIMARY KEY("transactionId")
);


ALTER TABLE "transactions" ADD CONSTRAINT "fk_fromLudomanId" FOREIGN KEY ("fromLudomanId")
	REFERENCES "ludomans"("ludomanId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "transactions" ADD CONSTRAINT "fk_toLudomanId" FOREIGN KEY ("toLudomanId")
	REFERENCES "ludomans"("ludomanId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;


